# Generated by Django 5.0 on 2025-01-13 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rpa', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Aprovacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cpf', models.CharField(max_length=11, verbose_name='CPF')),
                ('status', models.CharField(choices=[('pendente', 'Pendente'), ('aprovado', 'Aprovado'), ('rejeitado', 'Rejeitado')], default='pendente', max_length=10, verbose_name='Status')),
            ],
            options={
                'verbose_name': 'Aprovação',
                'verbose_name_plural': 'Aprovações',
                'ordering': ['id'],
            },
        ),
        migrations.RemoveField(
            model_name='product',
            name='brand',
        ),
        migrations.RemoveField(
            model_name='product',
            name='category',
        ),
        migrations.DeleteModel(
            name='Brand',
        ),
        migrations.DeleteModel(
            name='Category',
        ),
        migrations.DeleteModel(
            name='Product',
        ),
    ]
